{"name": "Проверка логина c неправильным паролем", "status": "passed", "description": "Пытаемся залогиниться в аккаунт пользователя, получаем ошибку 401 и соотвествующее сообщение", "start": 1723629944992, "stop": 1723629945195, "uuid": "b63a38cc-dbf7-4123-8ec9-66972563ebf4", "historyId": "0a9292d29b3c8de0dc4c2560bad5138f", "testCaseId": "0a9292d29b3c8de0dc4c2560bad5138f", "fullName": "tests.test_login_user.TestLoginUser#test_no_such_password", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_login_user"}, {"name": "subSuite", "value": "TestLoginUser"}, {"name": "host", "value": "LAPTOP-NE0EJ4CA"}, {"name": "thread", "value": "8424-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_login_user"}]}